coc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('oth.urls', namespace='oth')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(), {'next_page': '/accounts/login/'}, name='logout'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oth/urls.py
from django.urls import path

from oth import views

app_name = 'oth'
urlpatterns = [
    path('', views.index, name='index'),
    path('answer/<int:pk>', views.answer, name='answer'),
    path('lboard/', views.lboard, name='lboard'),
    path('rules/', views.rules, name='rules'),
    path('finish/', views.finish, name='finish'),
    path('attachment/<int:pk>', views.view_video, name='attachment'),
    path('stay_tuned/', views.stay_tuned, name='stay_tuned'),
    path('video_feed', views.video_feed, name='video_feed'),
    path('not_happy', views.not_happy, name='not_happy'),

]

oth/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
# from django.contrib.auth import get_user_model

import datetime
import os


# User = get_user_model()


def get_upload_path(instance, filename):
    return os.path.join(
        "%s" % instance.module.module_number, filename)


class Module(models.Model):
    module_number = models.IntegerField()
    module_name = models.CharField(max_length=50)

    def __str__(self):
        return self.module_name


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    level = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    random_number = models.IntegerField(default=1)
    timestamp = models.DateTimeField()
    player_emotion = models.CharField(max_length=50, default='neutral', blank=True, null=True)
    video_viewed = models.IntegerField(default=0)
    base_module = models.ForeignKey(Module, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_upload_path, blank=True, null=True, default='images/level1.jpg')
    videofile = models.FileField(upload_to=get_upload_path, blank=True, null=True)
    audiofile = models.FileField(upload_to=get_upload_path, blank=True, null=True)
    question = models.TextField(null=True, blank=True)
    option1 = models.TextField(null=True, blank=True)
    option2 = models.TextField(null=True, blank=True)
    numuser = models.IntegerField(default=0)
    option1_level_score = models.IntegerField(default=0)
    option2_level_score = models.IntegerField(default=0)

    # accuracy = models.FloatField(default=0)
    wrong = models.IntegerField(default=0)

    def __str__(self):
        return '- '.join([str(self.module), self.question])

    class Meta:
        ordering = ['-pk']


class Answer(models.Model):
    user = models.ForeignKey(Player, on_delete=models.CASCADE, blank=True, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    sentiment = models.CharField(max_length=50, blank=True, null=True)
    facial_expression = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return '- '.join([self.user.name, str(self.question.module), self.question.question])


class Notif(models.Model):
    text = models.CharField(max_length=200)
    date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.text


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Emotion(models.Model):
    user = models.ForeignKey(Player, on_delete=models.CASCADE, blank=True, null=True)
    emotion = models.CharField(max_length=500, blank=True, null=True)
    timestamp = models.DateTimeField()

    def __str__(self):
        return '- '.join([self.user.name, self.emotion])

oth/views.py
from django.shortcuts import render
from oth import models
import datetime
from django.contrib.auth.decorators import login_required
import random
from django.shortcuts import redirect
from textblob import TextBlob
from django.http.response import StreamingHttpResponse
from oth.camera import VideoCamera
from django.shortcuts import HttpResponse
from django.contrib.humanize.templatetags.humanize import ordinal

# Create your views here.

m_level = 1
f_user = ""
last = 100


def get_emotion(player):
    """
    get_emotions function gets the MAX emotions count of user and saves automatically,
    when user answers the question
    """

    oneday = datetime.datetime.now() - datetime.timedelta(days=1)
    emotion_shivam = models.Emotion.objects.filter(user=player, timestamp__gt=oneday)
    if emotion_shivam:
        emotion_list = [emotion.emotion for emotion in emotion_shivam]
        bb = dict(zip(emotion_list, [emotion_list.count(i) for i in emotion_list]))
        final_emotion = max(bb, key=bb.get)
        player.player_emotion = final_emotion
        # player.save()


def sentiment(text):
    obj = TextBlob(text)
    polarity = obj.sentiment.polarity
    label = ''
    if -1 <= polarity < -0.5:
        label = 'very bad'
    elif -0.5 <= polarity < -0.1:
        label = 'bad'
    elif -0.1 <= polarity < 0.2:
        label = 'ok'
    elif 0.2 <= polarity < 0.6:
        label = 'good'
    elif 0.6 <= polarity <= 1:
        label = 'positive'

    return label


def save_profile(backend, user, response, *args, **kwargs):
    if backend.name == 'google-oauth2':
        profile = user
        try:
            player = models.Player.objects.get(user=profile)
        except:
            player = models.Player(user=profile)
            player.timestamp = datetime.datetime.now()
            player.name = response.get('name')
            player.save()


def save_answer(ans, question, player):
    """
    This function saves answer given by user.
    """
    s = sentiment(ans)
    answer, created = models.Answer.objects.update_or_create(user=player, question=question,
                                                             defaults={'answer': ans, 'sentiment': s})
    player.video_viewed = 0
    # player.save()
    # answer.image =
    # answer.facial_expression =
    if created:
        player.score = player.score + 10
        player.timestamp = datetime.datetime.now()
        question.numuser = question.numuser + 1
        # player.save()
        # question.save()


def one_day_limitation(request, player):
    """
    one_day_limitation restricts user to answer any question if he has already answered in time range of 24 hours
    """

    if (datetime.datetime.now(datetime.timezone.utc) - player.timestamp).days < 1:
        seconds = 86400 - (datetime.datetime.now(datetime.timezone.utc) - player.timestamp).total_seconds()
        seconds = seconds % (24 * 3600)
        hour = seconds // 3600
        seconds %= 3600
        minutes = seconds // 60
        seconds %= 60

    return render(request, 'oth/time_limit.html',
                  {'hours': int(hour), 'minutes': int(minutes), 'seconds': int(seconds)})


def user_question_assignment(player):
    if player.score == 50:
        if player.level == 7:
            player.base_module = models.Module.objects.get(module_number=2)
        elif player.level == 8:
            player.base_module = models.Module.objects.get(module_number=3)
        elif player.level == 9:
            player.base_module = models.Module.objects.get(module_number=4)
        elif player.level == 10:
            player.base_module = models.Module.objects.get(module_number=5)
        elif player.level == 11:
            player.base_module = models.Module.objects.get(module_number=6)
        # player.save()

    if player.score < 50:
        random_question = models.Question.objects.filter(module__module_number="0")
    elif player.score >= 50:
        questions_answered = (player.score - 50) / 10
        if not questions_answered:
            modules_solved = 0
        else:
            modules_solved = int(questions_answered / 5)
        final_module = player.base_module.module_number + modules_solved
        if final_module == 7 and questions_answered % 5 == 0:
            player.random_number = 100
            player.save()
            return redirect('oth:finish')
        else:
            random_question = models.Question.objects.filter(module__module_number=final_module)
        # elif final_module == 2:
        #     random_question = models.Question.objects.filter(module__module_number="2")
        # elif final_module == 3:
        #     random_question = models.Question.objects.filter(module__module_number="3")
        # elif final_module == 4:
        #     random_question = models.Question.objects.filter(module__module_number="4")
        # elif final_module == 5:
        #     random_question = models.Question.objects.filter(module__module_number="5")
        # elif final_module == 6:
        #     random_question = models.Question.objects.filter(module__module_number="6")
        # elif final_module == 7:
        #     random_question = models.Question.objects.filter(module__module_number="7")

    random_number = random_question[random.randrange(0, random_question.count())].id
    while models.Answer.objects.filter(user=player, question_id=random_number).exists():
        random_number = random_question[random.randrange(0, random_question.count())].id

    player.random_number = random_number

    global m_level
    global f_user
    if m_level < player.level:
        m_level = player.level
        f_user = player.name

    # player.save()


@login_required
def index(request):
    user = request.user
    if user.is_authenticated:
        player = models.Player.objects.get(user_id=request.user.pk)
        get_emotion(player)
        if player.random_number == 100:
            return redirect('oth:finish')
        time_delta = (datetime.datetime.now(datetime.timezone.utc) - player.timestamp)

        # one_day_limitation(request, player)

        if player.random_number == 1:
            random_number = models.Question.objects.last().id
            question = models.Question.objects.get(pk=random_number)
        else:
            question = models.Question.objects.get(pk=player.random_number)

        return render(request, 'oth/level.html', {'player': player, 'level': question})
    #     except:
    #         global last
    #         if player.level > last:
    #             return render(request, 'oth/win.html', {'player': player})
    #         return render(request, 'oth/stay_tuned.html', {'player': player})
    # return render(request, 'oth/oth.html')


@login_required
def answer(request, **kwargs):
    player = models.Player.objects.get(user_id=request.user.pk)

    """
    The two line code below redirects User to not happy page, if player's emotion is not happy.
    """
    # if not 'happy'.__eq__(player.player_emotion):
    #     return redirect('oth:not_happy')

    # one_day_limitation(request, player)

    question = models.Question.objects.get(pk=kwargs['pk'])

    get_emotion(player)

    if request.method == 'POST':
        if request.POST.get('option'):
            """
            If user answers an MCQ question, this condition is selected.
            In this case, User's level increases by the option's level of the question he selects.
            """

            ans = request.POST.get('option')

            if ans == "option1":
                player.level += question.option1_level_score
                ans = question.option1
            elif ans == "option2":
                player.level += question.option2_level_score
                ans = question.option2
            # player.save()

            save_answer(ans, question, player)


        elif request.POST.get('answer'):
            """
            If user writes an answer to a Non-MCQ question, this condition is selected.
            In this case, user's level increases by 1.
            """

            ans = request.POST.get('answer')
            player.level += 1
            # player.save()

            save_answer(ans, question, player)

    try:

        user_question_assignment(player)
        player.save()
        question.save()
        return redirect('oth:index')

    except ValueError:
        return redirect('oth:finish')

    # global last
    # if player.level > last:
    #     return render(request, 'oth/win.html', {'player': player})


@login_required
def lboard(request):
    players = models.Player.objects.order_by('-score', 'timestamp')
    cur_rank = 1
    for player in players:
        player.rank = cur_rank
        cur_rank += 1

    return render(request, 'oth/lboard.html', {'players': players})


@login_required()
def rules(request):
    return render(request, 'oth/rules.html')


def finish(request):
    return render(request, 'oth/finish2.html')


def stay_tuned(request):
    return render(request, 'oth/stay_tuned.html')


def view_video(request, **kwargs):
    player = models.Player.objects.get(user_id=request.user.pk)
    video_view_count = player.video_viewed
    counts_remaining = 3 - player.video_viewed
    question = models.Question.objects.get(pk=kwargs['pk'])

    if video_view_count < 3:
        player.video_viewed += 1
        player.save()
        return render(request, 'oth/video.html',
                      {'question': question, 'player': player, 'counts_remaining': counts_remaining})

    return render(request, 'oth/video.html', {'player': player})


def not_happy(request, **kwargs):
    player = models.Player.objects.get(user_id=request.user.pk)

    return render(request, 'oth/not_happy.html', {'player_emotion': player.player_emotion})


def gen(camera, player):
    while True:
        frame, emotion = camera.get_frame()
        # print(emotion, player)
        player_object = models.Player.objects.get(user_id=player)

oth/templates/oth/finish.html
{% load static %}

<html>

<!--background audio-->
<title>Game Over</title>

<audio autoplay="autoplay" loop="true">
    <source src="/static/music3.mp3"/>
</audio>


<head>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/stars.css' %}" rel="stylesheet">


</head>
<body class="hidden">
<div id='stars'></div>
<div id='stars2'></div>
<div id='stars3'></div>
<div id='title'>
		
  		<span>
    		CONGRATULATIONS!!
  		</span>
    <br>
    <span>
    		YOU HAVE FINISHED THE CHALLENGE!!
        <span>
        <a href="{% url 'logout' %}"><small>LOGOUT</small></a></span>
  		</span>


</div>


</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $('div.hidden').fadeIn(50000).removeClass('hidden');
    });
</script>
</html>

oth/templates/oth/lboard.html
{%extends 'base.html'%}

{%block content%}

      <div class="row">
        <h1 class="lboardh1">Leaderboard</h1>
        
        <div class="col-lg-8 col-lg-offset-2" style="">
          
            {% if players %}
            <div class="table-responsive">
            <table  class="table table-hover table-striped table-bordered "  style="font-weight:bold;box-shadow: 0px 0px 8px #000">
                <tr style="background-color:#457fca;color:#fff;font-size:18px"> 
                	<th>#</th><th >Player Name</th><th>Player Score</th><th>Last level Crossed at</th>
                </tr>
                {% for player in players %}
                <tr>
                	<td>{{ player.rank }}</td><td>{{ player.name }}</td>    <td> {{player.score}} </td>    <td> {{player.timestamp}}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
        {% else %}
            <strong>There are no players present.</strong>
        {% endif %}

		<a href="/"><button type="button" class="btn btn-primary btn-lg " style="margin-top:10px;">Go Back</button></a>

        </div>

      </div>

{%endblock%}

oth/templates/oth/level.html
{% extends 'base.html' %}

{% block content %}
    <script>
        var myWindow;

        function openWin() {
            myWindow = window.open('popup_video', "myWindow", "width=650,height=500", 1000);
            myWindow.document.write("<img src=\"{% url 'oth:video_feed' %}\" role=\"button\" tabIndex=\"0\">\n");
        }

        function closeWin() {
            myWindow.close();
        }
    </script>

    <!-- Example row of columns -->
    <div class="row">

        {% if user and not user.is_anonymous %}

            <nav class="navbar navbar-default">
                <div class="container1">
                    <div class="navbar-header">
                        <button style="background-color:#f5f5f5" type="button" class="navbar-toggle"
                                data-toggle="collapse"
                                data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" style="color:#000" class="navbar-brand"><span>🔍</span><span
                                style="margin-left:10px;font-family: 'Creepster', cursive;font-size:20px;opacity: 0.8;">COURTESY ONLINE CHALLENGE</span>
                        </a>
                        <div class="navbar-brand" style="font-family:'Capriola',sans-serif;">Your Score : <span
                                style="font-weight:bold;color:#5CB85C">{{ player.score }} points</span></div>
                        <div class="navbar-brand" style="font-family:'Capriola',sans-serif;">Your Level : <span
                                style="font-weight:bold;color:#5CB85C">{{ player.level }}</span></div>
                        {% if player.player_emotion is not '' %}
                            <div class="navbar-brand" style="font-family:'Capriola',sans-serif;">You seem to be <span
                                    style="font-weight:bold;color:#5CB85C">{{ player.player_emotion }}</span> Today.
                            </div>
                        {% endif %}

                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav navbar-right">


                            {#                            <button onclick="closeWin()">Close "myWindow"</button>#}


                            <li><a style="font-family:'Capriola',sans-serif;" href="{% url 'oth:rules' %}">Rules</a>
                            </li>
                            <li><a style="font-family:'Capriola',sans-serif;"
                                   href="{% url 'oth:lboard' %}">Leaderboard</a>
                            </li>
                            <li>
                                <button class="dropdown-toggle btn btn-default navbar-btn"
                                        style="margin-left:10px;background-color:#f5f5f5" onclick="openWin()"><b>How do
                                    you
                                    Feel?</b>
                                </button>
                            </li>
                            <li class="dropdown">
                                <button class="dropdown-toggle btn btn-default navbar-btn" data-toggle="dropdown"
                                        style="margin-left:10px;background-color:#f5f5f5">

                                    <b>{{ user.get_full_name|default:user.username }}</b>

                                    <span class="caret"></span>
                                </button>

                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'logout' %}"><b>Logout</b></a></li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>


        {% endif %}


        <!-- Jumbotron -->
        {% if level.image %}
            <div class="jumbotron border-shadow" style="margin-top:15px;background-color:rgba(255, 255, 255, 0.4);">
                <img style="" src="{{ level.image.url }}" width="400px"/>
            </div>
        {% endif %}

        <div class="col-lg-8 rules border-shadow" style="padding:25px">

            </br>
            <div class="lead" style="padding:10px; font-family: 'Montserrat', sans-serif;  ">
                {% if level.question %}
                    <div>
                        <strong>Q:</strong>
                        {{ level.question }}
                    </div>
                {% endif %}
                <hr>
                {% if level.option1 %}
                    <div class="col-lg-6 table-bordered" style="height: 200px"><strong>Option 1:</strong>
                        {{ level.option1 }}
                    </div>

                {% endif %}
                {% if level.option2 %}
                    <div class="col-lg-6 table-bordered" style="height: 200px"><strong>Option 2:</strong>
                        {{ level.option2 }}
                    </div>
                {% endif %}

            </div>
            </br>
            <br>
            <br>

            <div class="col-lg-12" style="height: 80px"><h3><strong>Enter your answer:</strong></h3>
                <br>
            </div>
            <form id="ans" method="post" action="{% url 'oth:answer' level.id %}">
                {% csrf_token %}
                <br>
                {% if level.option1 %}
                    <div class="col-lg-6 table-bordered" style="height: 80px">
                        <input type="radio" id="option1" name="option" value="option1">
                        <label for="option1"><h4><strong>OPTION 1</strong></h4></label><br>
                    </div>
                    <div class="col-lg-6 table-bordered" style="height: 80px">
                        <input type="radio" id="option2" name="option" value="option2">
                        <label for="option2"><h4><strong>OPTION 2</strong></h4></label><br>
                    </div>
                {% endif %}
                {% if not level.option1 %}
                    <br> <input type="text" name="answer" class="form-control" style="height: 50px" value="" size="500"
                                autofocus/>
                    <br/>
                {% endif %}

                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit"/>
            </form>
        </div>

        <div class="col-lg-4">
            <div class="sidebox border-shadow" style="padding:15px">
                <p style="text-align:center;font-size:35px;color:green">{{ level.module }}</p>
            </div>
            <br>

        </div>
        {% if level.videofile %}
            <div class="col-lg-4">
                <div class="sidebox border-shadow" style="padding:15px">
                    <a style="text-align:center;font-size:35px;color:green" href="{% url 'oth:attachment' level.id %}">View
                        Video</a>
                </div>
                <br>
            </div>

        {% endif %}
        {% if level.audiofile %}
            <div class="col-lg-4">
                <div class="sidebox border-shadow" style="padding:15px">
                    <a style="text-align:center;font-size:35px;color:green" href="{% url 'oth:attachment' level.id %}">Listen
                        Audio</a>
                </div>
                <br>
            </div>
        {% endif %}

    </div>
{% endblock %}

oth/templates/oth/not_happy.html
{% extends 'base.html' %}
{% block content %}

    {% if user and not user.is_anonymous %}

        <nav class="navbar navbar-default">
            <div class="container1">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" style="color:#000" class="navbar-brand"><span>🔍</span><span
                            style="margin-left:10px;font-family: 'Creepster', cursive;font-size:20px;opacity: 0.8;">Courtesy Online Challenge</span>
                    </a>
                    <div class="navbar-brand">Your Score : <span
                            style="font-weight:bold;color:#5CB85C">{{ player.score }} points</span></div>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">

                        <li><a href="{% url 'oth:rules' %}">Rules</a></li>
                        <li><a href="{% url 'oth:lboard' %}">Leaderboard</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <button class="dropdown-toggle btn btn-default navbar-btn" data-toggle="dropdown"
                                    style="margin-left:10px">

                                <b>{{ user.get_full_name|default:user.username }}</b>

                                <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu">
                                <li><a href="{% url 'logout' %}"><b>Logout</b></a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>


        <audio autoplay="autoplay" loop>
            <source src="/static/hp-theme.mp3"/>
        </audio>
    {% endif %}

    <!-- Jumbotron -->
    <div class="jumbotron border-shadow" style="margin-top:15px;background-color:#eee">
        <h3> Our Intelligenge says that you are not happy enough to answer the question. You seem to be {{ player_emotion }}</h3>

    <h3>Let us know you more. Let the AI decide.</h3>

    </div>


{% endblock %}

oth/templates/oth/stay_tuned.html
{% extends 'base.html' %}
{% block content %}

    {% if user and not user.is_anonymous %}

        <nav class="navbar navbar-default">
            <div class="container1">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" style="color:#000" class="navbar-brand"><span>🔍</span><span
                            style="margin-left:10px;font-family: 'Creepster', cursive;font-size:20px;opacity: 0.8;">Courtesy Online Challenge</span>
                    </a>
                    <div class="navbar-brand">Your Score : <span
                            style="font-weight:bold;color:#5CB85C">{{ player.score }} points</span></div>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">

                        <li><a href="{% url 'oth:rules' %}">Rules</a></li>
                        <li><a href="{% url 'oth:lboard' %}">Leaderboard</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <button class="dropdown-toggle btn btn-default navbar-btn" data-toggle="dropdown"
                                    style="margin-left:10px">

                                <b>{{ user.get_full_name|default:user.username }}</b>

                                <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu">
                                <li><a href="{% url 'logout' %}"><b>Logout</b></a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>


        <audio autoplay="autoplay" loop>
            <source src="/static/hp-theme.mp3"/>
        </audio>
    {% endif %}

    <!-- Jumbotron -->
    <div class="jumbotron border-shadow" style="margin-top:15px;background-color:#eee">
        <h1> Stay tuned! More levels to be added!</h1>

    </div>


{% endblock %}

oth/templates/oth/time_limit.html
{% extends 'base.html' %}
{% block content %}

    {% if user and not user.is_anonymous %}

        <nav class="navbar navbar-default">
            <div class="container1">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" style="color:#000" class="navbar-brand"><span>🔍</span><span
                            style="margin-left:10px;font-family: 'Creepster', cursive;font-size:20px;opacity: 0.8;">Courtesy Online Challenge</span>
                    </a>
                    <div class="navbar-brand">Your Score : <span
                            style="font-weight:bold;color:#5CB85C">{{ player.score }} points</span></div>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">

                        <li><a href="{% url 'oth:rules' %}">Rules</a></li>
                        <li><a href="{% url 'oth:lboard' %}">Leaderboard</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <button class="dropdown-toggle btn btn-default navbar-btn" data-toggle="dropdown"
                                    style="margin-left:10px">

                                <b>{{ user.get_full_name|default:user.username }}</b>

                                <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu">
                                <li><a href="{% url 'logout' %}"><b>Logout</b></a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>


        <audio autoplay="autoplay" loop>
            <source src="/static/hp-theme.mp3"/>
        </audio>
    {% endif %}

    <!-- Jumbotron -->
    <div class="jumbotron border-shadow" style="margin-top:15px;background-color:#eee">
        <h3> Please be back by {{ hours }} Hours : {{ minutes }} Minutes : {{ seconds }} Seconds</h3>

{#    <h3>Let us know you more. Let the AI decide.</h3>#}

    </div>


{% endblock %}